(TeX-add-style-hook
 "mybib-novenue"
 (lambda ()
   (LaTeX-add-bibitems
    "CaiFoHoNa24"
    "ZhangCaNaRu24"
    "LeeNaZe24"
    "LiuWaCuNa24"
    "CheNa23"
    "CaiNaYa23"
    "BoyarskyNaPo23"
    "NamkoongDaBa24"
    "JeongNa22"
    "LiNaXi24"
    "NamkoongMaGl22"
    "WortsmanIlGaRoGoMoNaFaCaKoSc22"
    "WortsmanIlLiKiHaFaNaSc22"
    "YadlowskyNaBaDuTi22"
    "NamkoongKeYaBr20"
    "DuchiHaNa22"
    "DuchiNa21"
    "DuchiGlNa21"
    "SinhaNaVoDu18"
    "DuchiNa19"
    "VolpiNaSeDuMuSa18"
    "OKellySiNaDuTe18"
    "HashimotoSrNaLi18"
    "NamkoongSiYaDu17"
    "NamkoongDu16"))
 :bibtex)

